# -*- coding: utf-8 -*-
"""IndustrualAirPollution

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWr3JhEwQdFl-2bznBDwl6UEIJZxJxth
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('/content/datafile.csv')
orignalataset = dataset

dataset = dataset.fillna(dataset.mean())

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

mean_PM25 = dataset['Monthly mean/average concentrationPM2.5'].mean()
mean_PM10 = dataset['Monthly mean concentrationPM10'].mean()
mean_NO2 = dataset['Monthly mean concentrationNO2'].mean()
mean_SO2 = dataset['Monthly mean concentrationSO2'].mean()
mean_O3 = dataset['Monthly mean concentrationO3'].mean()

import matplotlib.pyplot as plt
import seaborn as sns

# Data
labels = ['PM 2.5', 'PM10', 'NO2', 'SO2', 'O3']
sizes = [mean_PM25, mean_PM10, mean_NO2, mean_SO2, mean_O3]

palette = sns.color_palette('muted', n_colors=5)

# Create the pie chart
plt.pie(sizes, labels=labels, colors=palette, autopct='%1.1f%%', startangle=90)

# Add a title
plt.title('Concerntration of air pollutants emitted due to industries in Bengaluru')

# Add a legend
plt.legend(loc="upper left", bbox_to_anchor=(1.0, 1.0))

# Show the chart
plt.show()

import matplotlib.pyplot as plt
import datetime as dt

# List of date strings in the MMM-YY format
dates_str = dataset['Month -Year']

# List of values to plot
values = dataset[['Monthly mean/average concentrationPM2.5', 'Monthly mean concentrationPM10', 'Monthly mean concentrationNO2', 'Monthly mean concentrationSO2','Monthly mean concentrationO3']]

# Convert dates to datetime objects
dates = [dt.datetime.strptime(date_str, '%b-%y').date() for date_str in dates_str]

# Create a line graph
plt.plot(dates, values)

# Set the x-axis format to month-year
plt.gcf().autofmt_xdate()

# Set the axis labels
plt.xlabel('Date')
plt.ylabel('Value')

# Set the title
plt.title('Line Graph of Value against Date')

# Add a legend
plt.legend(['PM2.5', 'PM10', 'NO2', 'SO2', 'O3'])

# Show the plot
plt.show()

